const db = globalThis.__B44_DB__ || { auth:{ isAuthenticated: async()=>false, me: async()=>null }, entities:new Proxy({}, { get:()=>({ filter:async()=>[], get:async()=>null, create:async()=>({}), update:async()=>({}), delete:async()=>({}) }) }), integrations:{ Core:{ UploadFile:async()=>({ file_url:'' }) } } };

import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { FileText, Download, Loader2, FileBarChart, Brain } from 'lucide-react';

import ChartCard from '@/components/ChartCard';
import EmptyState from '@/components/EmptyState';
import { getSalesSummary } from '@/lib/aiService';

export default function Reports() {
  const [summary, setSummary] = useState(null);
  const [predictions, setPredictions] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([
      getSalesSummary(),
      db.entities.ProductionRecommendation.list('-target_date', 100)
    ]).then(([s, p]) => {
      setSummary(s);
      setPredictions(p || []);
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  if (loading) {
    return <div className="flex items-center justify-center h-96"><Loader2 className="w-8 h-8 text-[hsl(152,56%,40%)] animate-spin" /></div>;
  }

  if (!summary) {
    return (
      <div className="p-4 lg:p-6">
        <h1 className="text-2xl font-bold text-[hsl(152,56%,12%)] tracking-tight mb-6">Reports</h1>
        <EmptyState
          icon={FileText}
          title="No Data Available"
          description="Import your sales data to generate reports."
          action={<Link to="/" className="px-4 py-2.5 rounded-xl bg-[hsl(152,50%,94%)] text-[hsl(152,56%,30%)] text-sm font-semibold">Import Data</Link>}
        />
      </div>
    );
  }

  const handleDownload = () => {
    const lines = [
      'GREEN EARTH CAFÉ — AI CONSULTANT REPORT',
      `Generated: ${new Date().toLocaleString()}`,
      '',
      '========================================',
      'SALES SUMMARY',
      '========================================',
      `Total Records: ${summary.totalRecords}`,
      `Unique Products: ${summary.uniqueProducts}`,
      summary.dateRange ? `Date Range: ${summary.dateRange.start} to ${summary.dateRange.end}` : 'Date Range: N/A',
      `Total Revenue: $${summary.totalRevenue.toLocaleString()}`,
      `Avg Daily Revenue: $${summary.avgDailyRevenue.toLocaleString()}`,
      `Total Units Sold: ${summary.totalQuantity}`,
      '',
      '========================================',
      'AI PREDICTIONS',
      '========================================',
      predictions.length > 0 ? `Target Date: ${predictions[0].target_date || 'N/A'}` : 'No predictions generated yet.',
      '',
      predictions.length > 0 ? predictions.map(p => `${p.product}: ${p.recommended_quantity} units (${p.confidence}% confidence)\n  ${p.reasoning}`).join('\n\n') : '',
      '',
      '========================================',
      'AI OVERALL ANALYSIS',
      '========================================',
      predictions[0]?.overall_analysis || 'No analysis available.',
      '',
      '========================================',
      'REVIEW STATUS',
      '========================================',
      predictions.length > 0 ? predictions.map(p => `${p.product}: ${p.status}${p.manager_name ? ` by ${p.manager_name}` : ''}`).join('\n') : 'No predictions to review.',
      '',
      '---',
      'Generated by Green Earth Café AI Consultant System.'
    ];
    const content = lines.join('\n');
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cafe-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-4 lg:p-6 space-y-6 max-w-[1200px] mx-auto">
      <div>
        <h1 className="text-2xl font-bold text-[hsl(152,56%,12%)] tracking-tight">Reports</h1>
        <p className="text-sm text-[hsl(152,10%,45%)] mt-1">Generate a comprehensive report from your data</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white rounded-2xl border border-[hsl(150,15%,92%)] p-5">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[hsl(152,56%,30%)] to-[hsl(140,60%,45%)] flex items-center justify-center mb-4">
            <FileText className="w-6 h-6 text-white" />
          </div>
          <h3 className="font-semibold text-base text-[hsl(152,56%,12%)]">Full Operations Report</h3>
          <p className="text-xs text-[hsl(152,10%,45%)] mt-1.5 leading-relaxed">
            Includes sales summary, AI predictions with reasoning, overall analysis, and review status.
          </p>
          <div className="mt-4 space-y-1.5">
            <div className="flex items-center gap-2 text-xs text-[hsl(152,10%,50%)]"><div className="w-1 h-1 rounded-full bg-[hsl(152,56%,40%)]" /> {summary.totalRecords} sales records</div>
            <div className="flex items-center gap-2 text-xs text-[hsl(152,10%,50%)]"><div className="w-1 h-1 rounded-full bg-[hsl(152,56%,40%)]" /> {predictions.length} AI predictions</div>
            <div className="flex items-center gap-2 text-xs text-[hsl(152,10%,50%)]"><div className="w-1 h-1 rounded-full bg-[hsl(152,56%,40%)]" /> AI analysis & insights</div>
            <div className="flex items-center gap-2 text-xs text-[hsl(152,10%,50%)]"><div className="w-1 h-1 rounded-full bg-[hsl(152,56%,40%)]" /> Review status summary</div>
          </div>
          <button
            onClick={handleDownload}
            className="mt-5 flex items-center justify-center gap-2 w-full py-2.5 rounded-xl bg-gradient-to-r from-[hsl(152,56%,30%)] to-[hsl(152,50%,35%)] text-white text-sm font-semibold hover:shadow-lg transition-all"
          >
            <Download className="w-4 h-4" />
            Download Report
          </button>
        </div>

        <div className="bg-gradient-to-br from-[hsl(152,56%,12%)] to-[hsl(152,50%,20%)] rounded-2xl p-5 text-white flex flex-col justify-between">
          <div>
            <Brain className="w-8 h-8 mb-3 opacity-80" />
            <h3 className="font-semibold text-base">AI Insights</h3>
            <p className="text-xs text-white/70 mt-1.5 leading-relaxed">
              {predictions[0]?.overall_analysis 
                ? predictions[0].overall_analysis.substring(0, 200) + (predictions[0].overall_analysis.length > 200 ? '...' : '')
                : 'Generate AI predictions to see insights here.'}
            </p>
          </div>
          {predictions.length === 0 && (
            <Link to="/" className="mt-4 text-center py-2.5 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-semibold transition-colors">
              Generate Predictions
            </Link>
          )}
        </div>
      </div>
    </div>
  );
}